using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Maps;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.MapEditor.UI;

[GenerateTypedNameReferences]
public sealed partial class StructureCategoryItemEntry : PanelContainer
{
    public StructureCategoryItemEntry(string itemName)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        EntryItemName.Text = itemName;
    }

    public void RegisterTexture(Texture texture)
    {
        IconTex.Texture = texture;
    }
}
